# An example scene file

[camera]
center = [7.0, 0.0, 7.0]
target = [0.0, 0.0, 3.0]
roll = 0.0

[light]
center = [5.0, -5.0, 10.0]

[[planes]]
center = [0.0, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
scale = 0.2
reflect = 0.55
texture = "textures/01tizeta_floor_d.png"

[[planes]]
center = [-12.0, 0.0, 0.0]
normal = [1.0, 0.0, 0.0]
scale = 0.2
texture = "textures/metal plate tex.png"

[[planes]]
center = [0.0, -12.0, 0.0]
normal = [0.0, 1.0, 0.0]
scale = 0.15
texture = "textures/04univ2.png"

[[planes]]
center = [0.0, 12.0, 0.0]
normal = [0.0, -1.0, 0.0]
scale = 0.15
texture = "textures/02camino.png"

[[molecules]]
mol2file = "trp.mol2"
center = [0.0, 0.0, 4.0]
atom_color = [0.0, 0.0, 1.0]
bond_color = [0.0, 0.0, 1.0]
mol_scale = 10.0
atom_scale = 0.25
bond_scale = 0.125
angle_x = 0.0
angle_y = 0.0
angle_z = 90.0
